In [4]:
import tensorflow as tf
a = tf.constant([1.0,2.0],name="a")
b = tf.constant([2.0,3.0],name="b")
result = a + b
sess = tf.Session()
sess.run(result)

array([ 3.,  5.], dtype=float32)

In [5]:
v = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
with sess.as_default():
    print(tf.clip_by_value(v,2.5,4.5).eval())

[[ 2.5  2.5  3. ]
 [ 4.   4.5  4.5]]


In [7]:
v = tf.constant([1.0,2.0,3.0])
with sess.as_default():
    print(tf.log(v).eval())

[ 0.          0.69314718  1.09861231]


In [9]:
v1 = tf.constant([[1.0,2.0],[3.0,4.0]])
v2 = tf.constant([[5.0,6.0],[7.0,8.0]])
with sess.as_default():
    print((v1*v2).eval())
    print(tf.matmul(v1,v2).eval())

[[  5.  12.]
 [ 21.  32.]]
[[ 19.  22.]
 [ 43.  50.]]


In [10]:
v = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
with sess.as_default():
    print(tf.reduce_mean(v).eval())

3.5


In [11]:
cross_entropy = tf.nn.softmax_cross_entropy_with_logits(y,y_)


NameError: name 'y' is not defined

In [12]:
loss = tf.reduce_sum(tf.select(tf.greater(v1,v2),(v1-v2)*a,(v2-v1)*b))

AttributeError: module 'tensorflow' has no attribute 'select'

In [17]:
v1 = tf.constant([1.0,2.0,3.0,4.0])
v2 = tf.constant([4.0,3.0,2.0,1.0])
with sess.as_default():
    print(tf.greater(v1,v2).eval())
    print(tf.where(tf.greater(v1,v2),v1,v2).eval())

[False False  True  True]
[ 4.  3.  3.  4.]


In [19]:
import tensorflow as tf
from numpy.random import RandomState
batch_size = 8
# 两个输入节点
x = tf.placeholder(tf.float32,shape=(None,2),name='x-input')
# 回归问题一般只有一个输出节点
y_ = tf.placeholder(tf.float32,shape=(None,1),name='y-input')

#定义了一个单层的神经网络前向传播的过程，这里就是简单加权和
w1 = tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))
y = tf.matmul(x,w1)

# 定义预测多了和预测少了的成本
loss_less = 10
loss_more = 1
loss = tf.reduce_sum(tf.where(tf.greater(y,y_),
                              (y-y_)*loss_more,
                              (y_-y)*loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)
# 通过随机数生成一个模拟数据集
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size,2)
# 设置回归的正确值为两个输入的和加上一个随机变量。之所以要加上一个随机量是为了加入不可预测的噪音，
# 否则不同损失函数的意义就不大了，因为不同损失函数都会在能完全预测正确的时候最低。一般来说噪音为
#一个均值为0的小量，所以这里的噪音设置为-0.05~0.05的随机数。
Y = [[x1+x2+rdm.rand()/10.0-0.05] for (x1,x2) in X]

# 训练神经网路
with tf.Session() as sess:
    init_op = tf.initialize_all_variables()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i * batch_size) % dataset_size
        end = min(start+batch_size,dataset_size)
        sess.run(train_step,feed_dict = {x:X[start:end],y_:Y[start:end]})
        print(sess.run(w1))


Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[-0.81031823]
 [ 1.4855988 ]]
[[-0.8093366]
 [ 1.4865911]]
[[-0.80838311]
 [ 1.48758912]]
[[-0.80742168]
 [ 1.48854196]]
[[-0.80644417]
 [ 1.4894979 ]]
[[-0.80545688]
 [ 1.49047196]]
[[-0.80446237]
 [ 1.49145281]]
[[-0.8034634 ]
 [ 1.49243844]]
[[-0.80245554]
 [ 1.49342489]]
[[-0.80146426]
 [ 1.49441588]]
[[-0.80048096]
 [ 1.49542165]]
[[-0.79950386]
 [ 1.4964081 ]]
[[-0.79850495]
 [ 1.49741769]]
[[-0.79752892]
 [ 1.49840248]]
[[-0.79654419]
 [ 1.4994123 ]]
[[-0.79556257]
 [ 1.50043571]]
[[-0.79462433]
 [ 1.50143182]]
[[-0.79369748]
 [ 1.50242686]]
[[-0.79274493]
 [ 1.50342429]]
[[-0.79180086]
 [ 1.50438201]]
[[-0.79083252]
 [ 1.50532436]]
[[-0.78985554]
 [ 1.50629151]]
[[-0.78887033]
 [ 1.50725818]]
[[-0.78787929]
 [ 1.50822437]]
[[-0.78687394]
 [ 1.50918674]]
[[-0.78588563]
 [ 1.51015079]]
[[-0.78490686]
 [ 1.51113391]]
[[-0.7839362 ]
 [ 1.51209509]]
[[-0.78293514]
 [ 1.51309192]]
[[-0.7819587 ]
 [ 1.51406181]

[[-0.5205791 ]
 [ 1.75703418]]
[[-0.51965731]
 [ 1.75783336]]
[[-0.51873869]
 [ 1.75862539]]
[[-0.51780021]
 [ 1.75944161]]
[[-0.5168457 ]
 [ 1.76027942]]
[[-0.5158658 ]
 [ 1.76112127]]
[[-0.51492459]
 [ 1.76190579]]
[[-0.51400596]
 [ 1.76269186]]
[[-0.51309812]
 [ 1.76344621]]
[[-0.51213527]
 [ 1.76428771]]
[[-0.51120889]
 [ 1.7650826 ]]
[[-0.51027215]
 [ 1.76592815]]
[[-0.509354  ]
 [ 1.76676488]]
[[-0.50848186]
 [ 1.76759315]]
[[-0.50763065]
 [ 1.76842248]]
[[-0.50674385]
 [ 1.76925504]]
[[-0.50586319]
 [ 1.7700597 ]]
[[-0.50493956]
 [ 1.77086413]]
[[-0.50401908]
 [ 1.77166128]]
[[-0.5030787 ]
 [ 1.77248287]]
[[-0.50212228]
 [ 1.77332604]]
[[-0.50114036]
 [ 1.77417338]]
[[-0.50019723]
 [ 1.7749629 ]]
[[-0.49927679]
 [ 1.77575397]]
[[-0.49836719]
 [ 1.7765131 ]]
[[-0.49740243]
 [ 1.77735996]]
[[-0.49647427]
 [ 1.77815986]]
[[-0.4955357 ]
 [ 1.77901077]]
[[-0.49461582]
 [ 1.77985275]]
[[-0.49374208]
 [ 1.78068614]]
[[-0.49288931]
 [ 1.78152061]]
[[-0.49200091]
 [ 1.78235829]]
[[-0.491

[[-0.27834037]
 [ 1.96216071]]
[[-0.27749136]
 [ 1.96281564]]
[[-0.27662995]
 [ 1.96348667]]
[[-0.27574852]
 [ 1.96414411]]
[[-0.27489352]
 [ 1.96476531]]
[[-0.27404937]
 [ 1.9654144 ]]
[[-0.27322215]
 [ 1.966012  ]]
[[-0.27234381]
 [ 1.96669567]]
[[-0.27149689]
 [ 1.96733868]]
[[-0.2706598 ]
 [ 1.96799493]]
[[-0.26987037]
 [ 1.96859765]]
[[-0.26914638]
 [ 1.96915102]]
[[-0.26843029]
 [ 1.9697355 ]]
[[-0.2676588 ]
 [ 1.97035885]]
[[-0.26687804]
 [ 1.97098196]]
[[-0.26603732]
 [ 1.9716332 ]]
[[-0.26518717]
 [ 1.9723016 ]]
[[-0.26433775]
 [ 1.97295702]]
[[-0.26347557]
 [ 1.97362912]]
[[-0.26259306]
 [ 1.97428799]]
[[-0.26173687]
 [ 1.97491062]]
[[-0.26089138]
 [ 1.97556186]]
[[-0.26006269]
 [ 1.97616148]]
[[-0.25918254]
 [ 1.97684813]]
[[-0.25833377]
 [ 1.977494  ]]
[[-0.25750995]
 [ 1.97813046]]
[[-0.25673234]
 [ 1.9787153 ]]
[[-0.25603232]
 [ 1.97922981]]
[[-0.25533754]
 [ 1.97977996]]
[[-0.2545847 ]
 [ 1.98037326]]
[[-0.25382039]
 [ 1.98096979]]
[[-0.25299391]
 [ 1.98159778]]
[[-0.252

 [ 2.09089637]]
[[-0.08072076]
 [ 2.09123135]]
[[-0.08005209]
 [ 2.09159589]]
[[-0.07937115]
 [ 2.09197474]]
[[-0.07864224]
 [ 2.09237885]]
[[-0.07791904]
 [ 2.09277725]]
[[-0.07722913]
 [ 2.09316397]]
[[-0.07653467]
 [ 2.09352756]]
[[-0.07583629]
 [ 2.09391928]]
[[-0.07517993]
 [ 2.09425807]]
[[-0.07457272]
 [ 2.09455228]]
[[-0.07398716]
 [ 2.09483075]]
[[-0.07346032]
 [ 2.09506702]]
[[-0.0729923 ]
 [ 2.09526038]]
[[-0.07245669]
 [ 2.09550834]]
[[-0.07190925]
 [ 2.09575629]]
[[-0.07129215]
 [ 2.0960505 ]]
[[-0.07065071]
 [ 2.09638405]]
[[-0.06998119]
 [ 2.09674811]]
[[-0.06929898]
 [ 2.09712696]]
[[-0.06856821]
 [ 2.0975318 ]]
[[-0.06784293]
 [ 2.09793115]]
[[-0.06715091]
 [ 2.09831905]]
[[-0.0664541 ]
 [ 2.09868383]]
[[-0.06575316]
 [ 2.09907746]]
[[-0.06509434]
 [ 2.09941792]]
[[-0.0644848 ]
 [ 2.09971333]]
[[-0.06389692]
 [ 2.09999323]]
[[-0.06336799]
 [ 2.10023046]]
[[-0.06289814]
 [ 2.10042453]]
[[-0.06236019]
 [ 2.10067391]]
[[-0.06181024]
 [ 2.10092354]]
[[-0.06119012]
 [ 2.101

 [ 2.17683172]]
[[ 0.10320546]
 [ 2.17696476]]
[[ 0.10369482]
 [ 2.17711425]]
[[ 0.10427345]
 [ 2.17733383]]
[[ 0.1048629 ]
 [ 2.17757607]]
[[ 0.1054958 ]
 [ 2.17787051]]
[[ 0.10611601]
 [ 2.17815471]]
[[ 0.10676914]
 [ 2.17844176]]
[[ 0.1073926]
 [ 2.1786902]]
[[ 0.10797251]
 [ 2.17891335]]
[[ 0.10857657]
 [ 2.1791327 ]]
[[ 0.1091776 ]
 [ 2.17937493]]
[[ 0.10974945]
 [ 2.17957616]]
[[ 0.11028237]
 [ 2.17974401]]
[[ 0.11077335]
 [ 2.17987418]]
[[ 0.11121488]
 [ 2.1799736 ]]
[[ 0.11160521]
 [ 2.18003964]]
[[ 0.11204414]
 [ 2.18014264]]
[[ 0.11251219]
 [ 2.18026543]]
[[ 0.11307255]
 [ 2.18046188]]
[[ 0.11364598]
 [ 2.18068385]]
[[ 0.11426511]
 [ 2.18096066]]
[[ 0.11487325]
 [ 2.18122911]]
[[ 0.1155161 ]
 [ 2.18150234]]
[[ 0.11613053]
 [ 2.18173838]]
[[ 0.11670242]
 [ 2.18195009]]
[[ 0.11729977]
 [ 2.18215942]]
[[ 0.11789513]
 [ 2.18239307]]
[[ 0.11846206]
 [ 2.18258643]]
[[ 0.11899065]
 [ 2.18274689]]
[[ 0.11947781]
 [ 2.18287039]]
[[ 0.11990983]
 [ 2.18295789]]
[[ 0.12029156]
 [ 2.18301

[[ 0.23771521]
 [ 2.20945621]]
[[ 0.23809814]
 [ 2.20946336]]
[[ 0.23852395]
 [ 2.20950484]]
[[ 0.2390319 ]
 [ 2.20960593]]
[[ 0.23952574]
 [ 2.20970488]]
[[ 0.24000254]
 [ 2.20979857]]
[[ 0.24044906]
 [ 2.20986652]]
[[ 0.24095725]
 [ 2.20996451]]
[[ 0.24145441]
 [ 2.21004105]]
[[ 0.24192275]
 [ 2.21010923]]
[[ 0.2424362 ]
 [ 2.21019244]]
[[ 0.24292073]
 [ 2.21027398]]
[[ 0.24339129]
 [ 2.21032739]]
[[ 0.24383511]
 [ 2.21035957]]
[[ 0.24424714]
 [ 2.21036386]]
[[ 0.24461071]
 [ 2.21033978]]
[[ 0.24492994]
 [ 2.21029043]]
[[ 0.24531534]
 [ 2.21029758]]
[[ 0.24574392]
 [ 2.21033931]]
[[ 0.24625519]
 [ 2.21044135]]
[[ 0.24675226]
 [ 2.21054125]]
[[ 0.2472322 ]
 [ 2.21063566]]
[[ 0.24768163]
 [ 2.21070433]]
[[ 0.24819314]
 [ 2.21080327]]
[[ 0.24869357]
 [ 2.21088052]]
[[ 0.24916498]
 [ 2.21094918]]
[[ 0.2496818 ]
 [ 2.21103311]]
[[ 0.25016949]
 [ 2.21111536]]
[[ 0.25064313]
 [ 2.21116924]]
[[ 0.25108987]
 [ 2.21120167]]
[[ 0.2515046 ]
 [ 2.21120596]]
[[ 0.25187057]
 [ 2.21118164]]
[[ 0.252

[[ 0.35660419]
 [ 2.20583773]]
[[ 0.35697567]
 [ 2.20575762]]
[[ 0.35733035]
 [ 2.20567489]]
[[ 0.35767713]
 [ 2.20559382]]
[[ 0.35800877]
 [ 2.20550156]]
[[ 0.35842738]
 [ 2.20546222]]
[[ 0.35884902]
 [ 2.20541286]]
[[ 0.35922205]
 [ 2.20533514]]
[[ 0.35966164]
 [ 2.20529079]]
[[ 0.36003336]
 [ 2.2052114 ]]
[[ 0.36039779]
 [ 2.2051053 ]]
[[ 0.36074862]
 [ 2.2049911 ]]
[[ 0.3610785 ]
 [ 2.20485878]]
[[ 0.36136711]
 [ 2.20470691]]
[[ 0.36161333]
 [ 2.20453405]]
[[ 0.36189619]
 [ 2.20439386]]
[[ 0.36220708]
 [ 2.20427394]]
[[ 0.36258006]
 [ 2.20419192]]
[[ 0.3629362 ]
 [ 2.20410728]]
[[ 0.3632845 ]
 [ 2.20402455]]
[[ 0.36361763]
 [ 2.20393062]]
[[ 0.36403841]
 [ 2.20389009]]
[[ 0.36446232]
 [ 2.20383954]]
[[ 0.36483735]
 [ 2.20376039]]
[[ 0.36527944]
 [ 2.20371509]]
[[ 0.36565325]
 [ 2.20363426]]
[[ 0.36601976]
 [ 2.20352674]]
[[ 0.36637262]
 [ 2.2034111 ]]
[[ 0.36670443]
 [ 2.20327735]]
[[ 0.36699471]
 [ 2.20312381]]
[[ 0.36724234]
 [ 2.20294905]]
[[ 0.36752689]
 [ 2.20280719]]
[[ 0.367

[[ 0.44904652]
 [ 2.17389059]]
[[ 0.44939423]
 [ 2.17372274]]
[[ 0.44973248]
 [ 2.17355013]]
[[ 0.45005256]
 [ 2.17336106]]
[[ 0.45033139]
 [ 2.17315292]]
[[ 0.45056731]
 [ 2.17292404]]
[[ 0.45084757]
 [ 2.17273569]]
[[ 0.45116231]
 [ 2.17257357]]
[[ 0.45154887]
 [ 2.17245722]]
[[ 0.45187619]
 [ 2.17230582]]
[[ 0.45220155]
 [ 2.17216206]]
[[ 0.45251614]
 [ 2.17201042]]
[[ 0.45288709]
 [ 2.17188597]]
[[ 0.45327103]
 [ 2.17175794]]
[[ 0.45360935]
 [ 2.17160392]]
[[ 0.4540298]
 [ 2.1714952]]
[[ 0.45438144]
 [ 2.17135143]]
[[ 0.45473126]
 [ 2.17118192]]
[[ 0.45507157]
 [ 2.17100763]]
[[ 0.45539361]
 [ 2.17081666]]
[[ 0.45567414]
 [ 2.17060661]]
[[ 0.45591149]
 [ 2.17037582]]
[[ 0.45619348]
 [ 2.1701858 ]]
[[ 0.45651016]
 [ 2.17002225]]
[[ 0.45689917]
 [ 2.16990495]]
[[ 0.45722854]
 [ 2.16975236]]
[[ 0.45755595]
 [ 2.1696074 ]]
[[ 0.45787251]
 [ 2.16945434]]
[[ 0.45824581]
 [ 2.16932893]]
[[ 0.4586322 ]
 [ 2.16919971]]
[[ 0.45897266]
 [ 2.16904449]]
[[ 0.4593958 ]
 [ 2.16893482]]
[[ 0.45974

 [ 2.09997678]]
[[ 0.55001354]
 [ 2.09965444]]
[[ 0.55022573]
 [ 2.09934855]]
[[ 0.55048853]
 [ 2.09908175]]
[[ 0.55081755]
 [ 2.09885764]]
[[ 0.55108994]
 [ 2.09860063]]
[[ 0.55131167]
 [ 2.09831882]]
[[ 0.55153614]
 [ 2.09803867]]
[[ 0.55183911]
 [ 2.09780097]]
[[ 0.55216932]
 [ 2.0975678 ]]
[[ 0.55245811]
 [ 2.09731221]]
[[ 0.55280709]
 [ 2.09708643]]
[[ 0.55309033]
 [ 2.09682894]]
[[ 0.55338347]
 [ 2.09654975]]
[[ 0.55367655]
 [ 2.09627271]]
[[ 0.55395836]
 [ 2.09598303]]
[[ 0.55420125]
 [ 2.09567714]]
[[ 0.55440241]
 [ 2.09535217]]
[[ 0.55461603]
 [ 2.0950439 ]]
[[ 0.55488056]
 [ 2.09477496]]
[[ 0.55521172]
 [ 2.09454894]]
[[ 0.5554859 ]
 [ 2.09428978]]
[[ 0.55570906]
 [ 2.09400582]]
[[ 0.55593503]
 [ 2.0937233 ]]
[[ 0.55624002]
 [ 2.09348369]]
[[ 0.55657238]
 [ 2.09324861]]
[[ 0.55686307]
 [ 2.09299088]]
[[ 0.55721432]
 [ 2.09276342]]
[[ 0.55749941]
 [ 2.09250379]]
[[ 0.55779445]
 [ 2.09222245]]
[[ 0.55808944]
 [ 2.09194326]]
[[ 0.55837309]
 [ 2.09165144]]
[[ 0.55861759]
 [ 2.091

 [ 2.00039172]]
[[ 0.61784452]
 [ 1.99998474]]
[[ 0.61800939]
 [ 1.99956715]]
[[ 0.61813807]
 [ 1.9991349 ]]
[[ 0.61829048]
 [ 1.99872768]]
[[ 0.61850899]
 [ 1.99837101]]
[[ 0.61874098]
 [ 1.99802184]]
[[ 0.61892271]
 [ 1.99764431]]
[[ 0.61905968]
 [ 1.99724662]]
[[ 0.6192112 ]
 [ 1.99685824]]
[[ 0.61946189]
 [ 1.99652517]]
[[ 0.61971003]
 [ 1.99617624]]
[[ 0.61992377]
 [ 1.99580979]]
[[ 0.62021703]
 [ 1.99548495]]
[[ 0.62044591]
 [ 1.99513018]]
[[ 0.62069523]
 [ 1.99475658]]
[[ 0.62089252]
 [ 1.9943527 ]]
[[ 0.62109047]
 [ 1.99394298]]
[[ 0.62125641]
 [ 1.99352252]]
[[ 0.62138593]
 [ 1.99308729]]
[[ 0.62153935]
 [ 1.99267733]]
[[ 0.62175924]
 [ 1.99231827]]
[[ 0.62199271]
 [ 1.99196684]]
[[ 0.62217563]
 [ 1.99158669]]
[[ 0.6223135 ]
 [ 1.99118626]]
[[ 0.62246597]
 [ 1.99079525]]
[[ 0.62271833]
 [ 1.99045992]]
[[ 0.62296808]
 [ 1.99010861]]
[[ 0.62318319]
 [ 1.98973966]]
[[ 0.62347829]
 [ 1.98941255]]
[[ 0.62370867]
 [ 1.9890554 ]]
[[ 0.6239596 ]
 [ 1.98867929]]
[[ 0.6241582 ]
 [ 1.988

[[ 0.68361795]
 [ 1.87669444]]
[[ 0.68386346]
 [ 1.87629116]]
[[ 0.68412405]
 [ 1.87589633]]
[[ 0.68432826]
 [ 1.87546933]]
[[ 0.68448216]
 [ 1.87501967]]
[[ 0.68465239]
 [ 1.8745805 ]]
[[ 0.68493402]
 [ 1.87420392]]
[[ 0.68521273]
 [ 1.87380946]]
[[ 0.68545282]
 [ 1.8733952 ]]
[[ 0.68578213]
 [ 1.87302792]]
[[ 0.68603921]
 [ 1.8726269 ]]
[[ 0.68631917]
 [ 1.87220466]]
[[ 0.68654072]
 [ 1.87174809]]
[[ 0.68676305]
 [ 1.87128496]]
[[ 0.68694937]
 [ 1.87080979]]
[[ 0.68709481]
 [ 1.87031794]]
[[ 0.68726707]
 [ 1.86985457]]
[[ 0.68751395]
 [ 1.86944878]]
[[ 0.68777609]
 [ 1.86905158]]
[[ 0.68798149]
 [ 1.86862195]]
[[ 0.68813628]
 [ 1.86816955]]
[[ 0.68830746]
 [ 1.86772764]]
[[ 0.68859071]
 [ 1.86734879]]
[[ 0.68887103]
 [ 1.86695194]]
[[ 0.68911248]
 [ 1.86653507]]
[[ 0.68944371]
 [ 1.86616552]]
[[ 0.68970227]
 [ 1.865762  ]]
[[ 0.68998384]
 [ 1.86533713]]
[[ 0.69020671]
 [ 1.86487782]]
[[ 0.69043028]
 [ 1.86441183]]
[[ 0.69061768]
 [ 1.86393368]]
[[ 0.69076395]
 [ 1.86343884]]
[[ 0.690

[[ 0.74852496]
 [ 1.73466873]]
[[ 0.74879038]
 [ 1.73421407]]
[[ 0.7489953 ]
 [ 1.73372483]]
[[ 0.74914628]
 [ 1.73321152]]
[[ 0.74931765]
 [ 1.73271108]]
[[ 0.74954009]
 [ 1.73224223]]
[[ 0.7497685 ]
 [ 1.73175824]]
[[ 0.74996197]
 [ 1.73125637]]
[[ 0.75026286]
 [ 1.730811  ]]
[[ 0.75048959]
 [ 1.73033142]]
[[ 0.75074804]
 [ 1.72983134]]
[[ 0.75094658]
 [ 1.72929585]]
[[ 0.75115085]
 [ 1.72875559]]
[[ 0.75131929]
 [ 1.72820413]]
[[ 0.75144595]
 [ 1.72763622]]
[[ 0.75160623]
 [ 1.72710204]]
[[ 0.75185329]
 [ 1.72663379]]
[[ 0.75212026]
 [ 1.72617662]]
[[ 0.75232637]
 [ 1.72568476]]
[[ 0.75247824]
 [ 1.72516859]]
[[ 0.75265056]
 [ 1.7246654 ]]
[[ 0.75287426]
 [ 1.72419393]]
[[ 0.75310397]
 [ 1.7237072 ]]
[[ 0.75329858]
 [ 1.72320259]]
[[ 0.75360119]
 [ 1.72275472]]
[[ 0.75382924]
 [ 1.72227252]]
[[ 0.75408924]
 [ 1.72176969]]
[[ 0.75428891]
 [ 1.72123122]]
[[ 0.75449437]
 [ 1.72068799]]
[[ 0.75466383]
 [ 1.72013354]]
[[ 0.7547912 ]
 [ 1.71956253]]
[[ 0.75495243]
 [ 1.71902549]]
[[ 0.755

 [ 1.58319354]]
[[ 0.8050037 ]
 [ 1.58259547]]
[[ 0.80512756]
 [ 1.58197916]]
[[ 0.80529004]
 [ 1.58139932]]
[[ 0.80554956]
 [ 1.58089113]]
[[ 0.80583233]
 [ 1.58039474]]
[[ 0.80604917]
 [ 1.57986021]]
[[ 0.80620718]
 [ 1.57929897]]
[[ 0.80638874]
 [ 1.57875168]]
[[ 0.80656946]
 [ 1.57821369]]
[[ 0.80676335]
 [ 1.57766151]]
[[ 0.80692446]
 [ 1.57709193]]
[[ 0.80720997]
 [ 1.57658613]]
[[ 0.80741805]
 [ 1.57604468]]
[[ 0.80768383]
 [ 1.57550561]]
[[ 0.80788523]
 [ 1.57492673]]
[[ 0.80809486]
 [ 1.57434189]]
[[ 0.80826646]
 [ 1.57374406]]
[[ 0.80839324]
 [ 1.57312751]]
[[ 0.80855858]
 [ 1.57254732]]
[[ 0.80882132]
 [ 1.57203889]]
[[ 0.80910724]
 [ 1.57154214]]
[[ 0.80932671]
 [ 1.57100689]]
[[ 0.80948693]
 [ 1.57044458]]
[[ 0.80967063]
 [ 1.5698961 ]]
[[ 0.80985343]
 [ 1.56935692]]
[[ 0.81004936]
 [ 1.56880319]]
[[ 0.81021219]
 [ 1.56823194]]
[[ 0.81049997]
 [ 1.5677247 ]]
[[ 0.81070983]
 [ 1.56718147]]
[[ 0.81097764]
 [ 1.5666405 ]]
[[ 0.81118071]
 [ 1.56605959]]
[[ 0.81139195]
 [ 1.565

[[ 0.85883462]
 [ 1.41820538]]
[[ 0.85911119]
 [ 1.41762555]]
[[ 0.85931849]
 [ 1.4170022 ]]
[[ 0.85953629]
 [ 1.41637194]]
[[ 0.85971349]
 [ 1.41572726]]
[[ 0.85984254]
 [ 1.41506195]]
[[ 0.86001509]
 [ 1.41443586]]
[[ 0.86022937]
 [ 1.4138577 ]]
[[ 0.86047661]
 [ 1.41329491]]
[[ 0.86065745]
 [ 1.41269279]]
[[ 0.86079907]
 [ 1.41209114]]
[[ 0.86097002]
 [ 1.41150379]]
[[ 0.86114305]
 [ 1.41092563]]
[[ 0.86133337]
 [ 1.41033125]]
[[ 0.86148977]
 [ 1.4097172 ]]
[[ 0.86178595]
 [ 1.40917206]]
[[ 0.86199844]
 [ 1.40858746]]
[[ 0.86227649]
 [ 1.408005  ]]
[[ 0.86248493]
 [ 1.40737891]]
[[ 0.86270392]
 [ 1.40674579]]
[[ 0.86288208]
 [ 1.40609825]]
[[ 0.86301184]
 [ 1.40542996]]
[[ 0.86318535]
 [ 1.40480101]]
[[ 0.86340082]
 [ 1.40422022]]
[[ 0.86364943]
 [ 1.40365493]]
[[ 0.86383122]
 [ 1.40305018]]
[[ 0.86397362]
 [ 1.40244591]]
[[ 0.86414552]
 [ 1.40185583]]
[[ 0.8643195 ]
 [ 1.40127516]]
[[ 0.86451083]
 [ 1.40067804]]
[[ 0.86466807]
 [ 1.40006125]]
[[ 0.86496586]
 [ 1.39951372]]
[[ 0.865

 [ 1.21181798]]
[[ 0.92752969]
 [ 1.21116424]]
[[ 0.927719  ]
 [ 1.21052599]]
[[ 0.92791063]
 [ 1.20989776]]
[[ 0.92812133]
 [ 1.20925188]]
[[ 0.92829454]
 [ 1.20858479]]
[[ 0.92862236]
 [ 1.20799255]]
[[ 0.92885756]
 [ 1.20735753]]
[[ 0.9291653 ]
 [ 1.20672476]]
[[ 0.92939603]
 [ 1.20604455]]
[[ 0.92963839]
 [ 1.20535684]]
[[ 0.92983556]
 [ 1.2046535 ]]
[[ 0.92997915]
 [ 1.20392776]]
[[ 0.93017113]
 [ 1.20324469]]
[[ 0.93040955]
 [ 1.20261395]]
[[ 0.93068463]
 [ 1.2019999 ]]
[[ 0.93088585]
 [ 1.20134318]]
[[ 0.93104345]
 [ 1.20068693]]
[[ 0.93123364]
 [ 1.20004618]]
[[ 0.93142617]
 [ 1.19941556]]
[[ 0.93163788]
 [ 1.1987673 ]]
[[ 0.93181193]
 [ 1.19809771]]
[[ 0.93214136]
 [ 1.19750321]]
[[ 0.9323777]
 [ 1.1968658]]
[[ 0.93268692]
 [ 1.19623065]]
[[ 0.93291873]
 [ 1.19554794]]
[[ 0.93316221]
 [ 1.19485772]]
[[ 0.93336034]
 [ 1.19415164]]
[[ 0.93350464]
 [ 1.19342315]]
[[ 0.93369758]
 [ 1.19273746]]
[[ 0.93387359]
 [ 1.19209254]]
[[ 0.93409276]
 [ 1.19146562]]
[[ 0.93424338]
 [ 1.19079

 [ 1.0589236 ]]
[[ 1.00244153]
 [ 1.05870831]]
[[ 1.00281549]
 [ 1.05853426]]
[[ 1.00327957]
 [ 1.05839026]]
[[ 1.00364757]
 [ 1.05814123]]
[[ 1.00401604]
 [ 1.0578357 ]]
[[ 1.00432527]
 [ 1.05746961]]
[[ 1.00462496]
 [ 1.05717218]]
[[ 1.00496221]
 [ 1.05687249]]
[[ 1.00539613]
 [ 1.05689478]]
[[ 1.00585163]
 [ 1.05686533]]
[[ 1.00621176]
 [ 1.05672693]]
[[ 1.00651073]
 [ 1.0565325 ]]
[[ 1.0067333 ]
 [ 1.05627453]]
[[ 1.00688696]
 [ 1.05600882]]
[[ 1.006989  ]
 [ 1.05568004]]
[[ 1.0072273 ]
 [ 1.05551577]]
[[ 1.00762713]
 [ 1.05537701]]
[[ 1.00800812]
 [ 1.0553273 ]]
[[ 1.00847876]
 [ 1.05529523]]
[[ 1.0088526 ]
 [ 1.05514693]]
[[ 1.00922644]
 [ 1.05493212]]
[[ 1.00954044]
 [ 1.0546478 ]]
[[ 1.00984442]
 [ 1.05442393]]
[[ 1.01018572]
 [ 1.05419052]]
[[ 1.01059437]
 [ 1.05420947]]
[[ 1.01102734]
 [ 1.05417693]]
[[ 1.01136708]
 [ 1.05403566]]
[[ 1.01164758]
 [ 1.05383861]]
[[ 1.01185334]
 [ 1.05357826]]
[[ 1.01199186]
 [ 1.05331028]]
[[ 1.01208007]
 [ 1.05297935]]
[[ 1.01222217]
 [ 1.052

[[ 1.01977324]
 [ 1.04316831]]
[[ 1.01969337]
 [ 1.04306912]]
[[ 1.01959646]
 [ 1.04289091]]
[[ 1.01953268]
 [ 1.0427618 ]]
[[ 1.01941073]
 [ 1.04254663]]
[[ 1.01933908]
 [ 1.04254246]]
[[ 1.01934648]
 [ 1.04249024]]
[[ 1.0193392 ]
 [ 1.04254055]]
[[ 1.01930463]
 [ 1.04251754]]
[[ 1.01922178]
 [ 1.04241562]]
[[ 1.01909554]
 [ 1.04229105]]
[[ 1.01897156]
 [ 1.0422256 ]]
[[ 1.01902235]
 [ 1.04229558]]
[[ 1.01906168]
 [ 1.04230344]]
[[ 1.0191803 ]
 [ 1.04249644]]
[[ 1.01930535]
 [ 1.04289722]]
[[ 1.01936233]
 [ 1.04314137]]
[[ 1.01945508]
 [ 1.04328191]]
[[ 1.01951349]
 [ 1.04331958]]
[[ 1.01958966]
 [ 1.04338491]]
[[ 1.01959336]
 [ 1.04334486]]
[[ 1.01963496]
 [ 1.04349768]]
[[ 1.01974475]
 [ 1.04358697]]
[[ 1.01982963]
 [ 1.04376447]]
[[ 1.01987779]
 [ 1.04385602]]
[[ 1.01986921]
 [ 1.04385746]]
[[ 1.01980948]
 [ 1.04382598]]
[[ 1.01971519]
 [ 1.04371011]]
[[ 1.01970005]
 [ 1.04360318]]
[[ 1.0196799 ]
 [ 1.04345179]]
[[ 1.01968515]
 [ 1.04338908]]
[[ 1.01970816]
 [ 1.04356015]]
[[ 1.019

In [ ]:
import tensorflow as tf
batch_size = n
# 每次读取一小部分数据作为当前的训练数据来执行反向传播算法。
x = tf.placeholder(tf.float32,shape=(batch_size,2),name='x-input')
y_ = tf.placeholder(tf.float32,shape=(batch_size,1),name='y-input')
# 定义神经网络结构和优化算法
loss = train_step = 

In [ ]:
import tensorflow as tf
# 获取一层神经网络的权重，并将这个权重的L2正则化损失加入名称为'losses'的集合中
def get_weight(shape, lambda):
    # 生成一个变量
    var = tf.Variable(tf.random_normal(shape), dtype=tf.float32)
    # add_to_collection函数将这个新生成变量的L2正则化损失项加入集合
    tf.add_to_collection('losses', tf.contrib.layers.l2_regularizer(lambda)(var))
    # 返回生成的变量
    return var
x = tf.placeholder(tf.float32,shape=(None,2))
y_ = tf.placeholder(tf.float32,shape=(None,1))
batch_size = 8
# 定义了每一层网络中节点的个数
layer_dimension = [2, 10, 10, 10, 1]
# 神经网络的层数
n_layers = len(layer_dimension)
# 这个变量维护前向传播时最深层的节点，开始的时候就是输入层。
cur_layer = x
# 当前层的节点个数
in_dimension = layer_dimension[0]
# 通过一个循环来生成5层全连接的神经网络结构
for i in range(1, n_layers):
    # layer_dimension[i]为下一层的节点个数
    out_dimension = layer_dimension[i]
    # 生成当前层中权重的变量，并将这个变量的L2正则化加入计算图上的集合
    weight = get_weight([in_dimension, out_dimension], 0.001)
    bias = tf.Variable(tf.constant(0.1,shape=[out_dimension]))
    # 使用ReLU激活函数
    cur_layer = tf.nn.relu(tf.matmul(cur_layer,weight) + bias)
    # 进入下一层之前将下一层的节点个数更新为当前层节点个数
    in_dimension = layer_dimension[i]

# 在定义神经网络前向传播的同时已经将所有的L2正则化损失加入了图上的集合，
#这里只需要计算刻画模型在训练数据上表现的损失函数
mse_loss = tf.reduce_mean(tf.square(y_ - cur_layer))    
# 将均方误差损失函数加入损失集合
tf.add_to_collection('losses', mse_loss)
# get_collection返回一个列表，这个列表是所有这个集合中的元素。在这个样例中，
# 这些元素就是损失函数的不同部分，将它们加起来就可以得到最终的损失函数。
mse_loss = tf.reduce_mean(tf.square(y_ - cur_layer))
# 将均方误差损失函数加入损失集合
tf.add_to_collection('losses', mse_loss)
# get_collection返回一个列表，这个列表是所有这个集合中的元素。在这个样例中，
# 这些元素就是损失函数的不同部分，将它们加起来就可以得到最终的损失函数
loss = tf.add_n(tf.get_collection('losses'))


In [2]:
import tensorflow as tf
# 定义一个变量用于计算滑动平均，这个变量的初始值为0.注意这里手动指定了变量的类型
# 为tf.float32,因为所有需要计算滑动平均的变量必须是实数型。
v1 = tf.Variable(0,dtype=tf.float32)
# 这里step变量模拟神经网络中迭代的轮数，可以用于动态控制衰减率。
step = tf.Variable(0, trainable = False)
# 定义一个滑动平均的类（class）。初始化时给定了衰减率（0.99）和控制衰减率的变量step。
ema = tf.train.ExponentialMovingAverage(0.99, step)
# 定义一个更新变量滑动平均的操作。这里需要给定一个列表，每次执行这个操作时
# 这个列表中的变量都会被更新。
maintain_averages_op = ema.apply([v1])
with tf.Session() as sess:
    # 初始化所有变量。
    init_op = tf.initialize_all_variables()
    sess.run(init_op)
    # 通过ema.average(v1)获取滑动平均之后变量的取值。在初始化之后变量v1的值和v1的滑动平均值都为0.
    print(sess.run([v1,ema.average(v1)]))
    # 更新变量v1的值到5
    sess.run(tf.assign(v1,5))
    # 更新v1的滑动平均值。衰减率为min{0.99,(1+step)/(10+step) = 0.1} = 0.1,
    # 所以v1的滑动平均会被更新为0.1*0+0.9*5 = 4.5
    sess.run(tf.assign(v1,5))
    print(sess.run([v1,ema.average(v1)]))
    
    # 更新step的值为10000
    sess.run(tf.assign(step,10000))
    # 更新v1的值为10.
    sess.run(tf.assign(v1,10))
    # 更新v1的滑动平均值。衰减率为min{0.99,(1+step)/(10+step) ==0.999} = 0.99,
    # 所以v1的滑动平均会被更新为0.99*4.5+0.01*10 = 4.555
    sess.run(maintain_averages_op)
    print(sess.run([v1,ema.average(v1)]))
    # 再次更新滑动平均值，得到的新滑动平均值
    sess.run(maintain_averages_op)
    print(sess.run([v1,ema.average(v1)]))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[0.0, 0.0]
[5.0, 0.0]
[10.0, 0.099999905]
[10.0, 0.19899981]
